import Head from 'next/head'
import React from 'react'
import { Footer } from './Footer'
import { Navbar } from './Navbar'

const Layout = ({children}) => {
  return (
    <>
      <Head>
        <title>Jaso Automation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main>
        {children}
      </main>
      <Footer></Footer>
    </>
  )
}

export default Layout